-- COMANDO PARA CRIAR BANCO DE DADOS
CREATE DATABASE HOTEL_PEDRO;
CREATE DATABASE HOTEL_PEDRO2;

-- COMANDO PARA APAGAR BANCO DE DADOS
DROP DATABASE HOTEL_PEDRO2;

-- COMANDO PARA APAGAR TABELAS
DROP TABLE FUNCIONARIOS; -- EXEMPLO

-- COMANDO PARA ATIVAR BANCO DE DADOSquartoquartopagamentopagamentohóspedehóspede
USE HOTEL_PEDRO;

-- COMANDO PARA CRIAR TABELAS
CREATE TABLE HÓSPEDE (
ID_HOSPEDE INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(60) NOT NULL,
CPF VARCHAR(14) NOT NULL UNIQUE,
EMAIL VARCHAR(60),
DATA_NASCIMENTO DATE NOT NULL,
TELEFONE VARCHAR(14),
DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE FUNCIONÁRIO (
ID_FUNCIONARIO INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(60) NOT NULL,
CARGO VARCHAR(60) NOT NULL,
TELEFONE VARCHAR(14) NOT NULL,
TURNO VARCHAR(50) NOT NULL,
CPF VARCHAR(14) NOT NULL UNIQUE
);

CREATE TABLE QUARTO (
ID_QUARTO INT AUTO_INCREMENT PRIMARY KEY,
STATUS_QUARTO CHAR(10),
CAPACIDADE VARCHAR(20) NOT NULL,
NUMERO_QUARTO INT NOT NULL UNIQUE,
QUANTIDADE_LEITOS VARCHAR(50) NOT NULL,
PRECO_DIARIA DECIMAL NOT NULL
);

CREATE TABLE CONSUMOS_GERAIS (
ID_CONSUMO INT AUTO_INCREMENT PRIMARY KEY,
TIPO_ALIMENTO VARCHAR(50) NOT NULL,
LOCAL_CONSUMO VARCHAR(50) NOT NULL,
VALOR_TOTAL DECIMAL (6,2) NOT NULL,
QUANTIDADE_CONSUMIDA INT NOT NULL,
DATA_CONSUMO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PAGAMENTO (
ID_PAGAMENTO INT AUTO_INCREMENT PRIMARY KEY,
NOME_CLIENTE VARCHAR(60) NOT NULL,
DESPESAS_TOTAL DECIMAL (6,2) NOT NULL,
DATA_PAGAMENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FORMA_PAGAMENTO VARCHAR(20) NOT NULL DEFAULT "CREDITO",
COMPROVANTE INT NOT NULL
);

