-- PROJETO SMARTCOFFEE_PEDRO
CREATE DATABASE IF NOT EXISTS SMARTCOFFEE_PEDRO;

USE SMARTCOFFEE_PEDRO;

CREATE TABLE IF NOT EXISTS CLIENTES (
ID_CLIENTES INT AUTO_INCREMENT PRIMARY KEY,
NOME_CLIENTES VARCHAR(50) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL,
TELEFONE_CLIENTES VARCHAR(14) NOT NULL,
EMAIL_CLIENTES VARCHAR(100) NOT NULL,
CPF VARCHAR(14) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS PRODUTOS (
ID_PRODUTOS INT AUTO_INCREMENT PRIMARY KEY,
NOME_PRODUTOS VARCHAR(50) NOT NULL,
VALOR_PRODUTOS DECIMAL(6,2) NOT NULL,
CATEGORIA_PRODUTOS VARCHAR(50) NOT NULL,
QUANTIDADE_PRODUTOS INT NOT NULL,
TAMAMHO_PRODUTO INT NOT NULL
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
ID_FUNCIONARIOS INT AUTO_INCREMENT PRIMARY KEY,
TELEFONE_FUNCIONARIOS VARCHAR(14) NOT NULL,
NOME_FUNCIONARIOS VARCHAR(50) NOT NULL,
ESCALA_FUNCIONARIOS TIME NOT NULL,
CARGO_FUNCIONARIOS VARCHAR(50) NOT NULL,
CPF VARCHAR(14) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS PEDIDOS (
ID_PEDIDOS INT AUTO_INCREMENT PRIMARY KEY,
VALOR_TOTAL DECIMAL (6,2) NOT NULL,
TIPO_PEDIDOS VARCHAR(50) NOT NULL,
STATUS_PEDIDOS VARCHAR(50) NOT NULL,
OBSERVACOES_PEDIDOS VARCHAR(50) NOT NULL,
DATA_PEDIDO DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS PAGAMENTO (
ID_PAGAMENTO INT AUTO_INCREMENT PRIMARY KEY,
NOME_CLIENTE VARCHAR(50) NOT NULL,
DESPESAS_TOTAL DECIMAL (6,2) NOT NULL,
DATA_PAGAMENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FORMA_PAGAMENTO ENUM ('CREDITO', 'DEBITO', 'PIX', 'DINHEIRO') DEFAULT 'CREDITO',
COMPROVANTE INT NOT NULL
);

CREATE TABLE IF NOT EXISTS ESTOQUE (
ID_ESTOQUE INT AUTO_INCREMENT PRIMARY KEY,
NOME_ITEM VARCHAR(50) NOT NULL,
QUANTIDADE_ATUAL DECIMAL(6,2) NOT NULL,
UNIDADE_PRODUTO VARCHAR(50) NOT NULL UNIQUE,
VALIDADE_PRODUTO DATE NOT NULL, 
FORNECEDOR_PRODUTO VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS DELIVERY (
ID_DELIVERY INT AUTO_INCREMENT PRIMARY KEY,
ENDERECO_ENTREGA VARCHAR(50) NOT NULL,
PREVISAO_ENTREGA DATETIME NOT NULL,
NOME_ENTREGADOR VARCHAR(50) NOT NULL,
STATUS_ENTREGA VARCHAR(50) NOT NULL,
TAXA_ENTREGA DECIMAL (3,2)
);
CREATE TABLE IF NOT EXISTS PROGRAMA_FIDELIDADE (
ID_FIDELIDADE INT AUTO_INCREMENT PRIMARY KEY,
NIVEL_FIDELIDADE VARCHAR(50) NOT NULL,
DATA_CADASTRO DATETIME NOT NULL,
PONTOS_ACUMULADOS INT NOT NULL,
DATA_ULTIMA_PONTUACAO DATETIME NOT NULL,
DATA_VALIDADE_PONTOS DATETIME NOT NULL
);