-- COMANDO PARA CRIAR BD
-- 1
--  CREATE DATABASE HOTEL_PEDRO;
-- VERIFICAR BD E CRIAR
--  CREATE DATABASE IF NOT EXISTS HOTEL_PEDRO;

-- ATIVAR O BD
-- 2
--  USE HOTEL_PEDRO;

-- 3
-- TABELAS
-- CREATE TABLE IF NOT EXISTS HOSPEDE (
-- ID_HOSPEDE INT AUTO_INCREMENT PRIMARY KEY,
-- NOME_HOSPEDE VARCHAR(50) NOT NULL,
-- TELEFONE VARCHAR(14) NOT NULL,
-- DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
-- CPF VARCHAR(14) NOT NULL UNIQUE,
-- DATA_NASCIMENTO DATETIME NOT NULL,
-- EMAIL_HOSPEDE VARCHAR(50) NOT NULL
-- );

-- CREATE TABLE IF NOT EXISTS QUARTO (
-- ID_QUARTO INT AUTO_INCREMENT PRIMARY KEY,
-- STATUS_QUARTO ENUM ('LIVRE', 'OCUPADO') DEFAULT 'LIVRE',
-- CAPACIDADE_QUARTO VARCHAR(20) NOT NULL,
-- NUMERO_QUARTO INT NOT NULL UNIQUE,
-- QUANTIDADE_LEITOS INT NOT NULL,
-- PRECO_DIARIA DECIMAL(6,2) NOT NULL DEFAULT 0.00
-- );

-- VISUALIZAR TABELAS
-- 4
-- SHOW TABLES;

-- 5 EM CASOS DE NECESSIDADE OU CORREÇÃO
-- APAGAR BD
-- DROP DATABASE HOTEL_PEDRO;
-- APAGAR TABLAS
-- DROP TABLES HOSPEDE;

-- COMANDOS PARA EXECUTAR CASO TENHA ESQUECIDO ALGO NAS TABELAS
-- INSERIR CAMPO
-- ALTER TABLE HOSPEDE ADD IDADE INT NOT NULL;

-- ALTERAR TIPOS DE DADOS
-- ALTER TABLE HOSPEDE MODIFY TELEFONE INT;

-- APAGAR COLUNA OU ATRIBUTO
-- ALTER TABLE ALUNOS DROP COLUMN TELEFONE; 

-- REMOMEAR TABELAS 
-- RENAME TABLE HOSPEDE TO ALUNOS;

-- APAGAR DADOS DE UMA TABELA
-- TRUNCATE TABLE ALUNOS;

-- INSERINDO DADOS NA TABELA
-- INSERT INTO ALUNOS (ID_HOSPEDE, NOME_HOSPEDE, TELEFONE_HOSPEDE, DATA_CADASTRO, CPF, DATA_NASCIMENTO, EMAIL_HOSPEDE) 
-- VALUES (1, 'PEDRO', 1, 'pedromiranda@gmail.com'),
-- (2, 'PEDRO', 2, 'pedromiranda@gmail.com');

-- INSERT INTO ALUNOS (ID_HOSPEDE, NOME_HOSPEDE, TELEFONE_HOSPEDE, CPF)
-- VALUES (3, 'PEDRO', 3, 'pedromiranda@gmail.com');

-- CONSULTAR DADOS EM UMA TABELA
-- SELECT * FROM ALUNOS;

-- INSERT INTO TABELA (CAMPO1, CAMPO2, CAMPO...N)
-- VALUES (VALOR1, VALOR2, VALOR...N)

CREATE TABLE IF NOT EXISTS PAGAMENTO (
ID_PAGAMENTO INT AUTO_INCREMENT PRIMARY KEY,
NOME_CLIENTE VARCHAR(50) NOT NULL,
DESPESAS_TOTAL DECIMAL (6,2) NOT NULL,
DATA_PAGAMENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FORMA_PAGAMENTO ENUM ('CREDITO', 'DEBITO', 'PIX', 'DINHEIRO') DEFAULT 'CREDITO',
COMPROVANTE INT NOT NULL
);

INSERT INTO PAGAMENTO (ID_PAGAMENTO, NOME_CLIENTE, DESPESAS_TOTAL, DATA_PAGAMENTO, FORMA_PAGAMENTO, COMPROVANTE)
VALUES (1, 'PEDRO', 250.00, '2026-08-20', default, '123');

INSERT INTO PAGAMENTO (ID_PAGAMENTO, NOME_CLIENTE, DESPESAS_TOTAL, DATA_PAGAMENTO, FORMA_PAGAMENTO, COMPROVANTE)
VALUES (2, 'NICOLAS', 260.00, '2026-08-21', default, '456'); 

INSERT INTO PAGAMENTO (ID_PAGAMENTO, NOME_CLIENTE, DESPESAS_TOTAL, DATA_PAGAMENTO, FORMA_PAGAMENTO, COMPROVANTE)
VALUES (3, 'MATHEUS', 270.00, '2026-08-22', default, '789');

INSERT INTO PAGAMENTO (ID_PAGAMENTO, NOME_CLIENTE, DESPESAS_TOTAL, DATA_PAGAMENTO, FORMA_PAGAMENTO, COMPROVANTE)
VALUES (4, 'RENNAN', 280.00, '2026-08-23', default, '067');

INSERT INTO PAGAMENTO (ID_PAGAMENTO, NOME_CLIENTE, DESPESAS_TOTAL, DATA_PAGAMENTO, FORMA_PAGAMENTO, COMPROVANTE)
VALUES (5, 'ENZO', 290.00, '2026-08-24', default, '254');

SELECT * FROM PAGAMENTO