CREATE DATABASE OFICINA_PEDRO;
USE OFICINA_PEDRO;

CREATE TABLE IF NOT EXISTS CLIENTES (
ID_CLIENTES INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(10) NOT NULL,
TELEFONE VARCHAR(15) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL,
CPF VARCHAR(14) NOT NULL UNIQUE,
EMAIL VARCHAR(50) NOT NULL
);

ALTER TABLE CLIENTES ADD IDADE INT NOT NULL;
ALTER TABLE CLIENTES DROP COLUMN IDADE;

CREATE TABLE IF NOT EXISTS VEICULOS (
ID_VEICULOS INT AUTO_INCREMENT PRIMARY KEY,
PLACA VARCHAR(20) NOT NULL,
ANO DATE NOT NULL,
MODELO VARCHAR(50) NOT NULL,
COR VARCHAR(50) NOT NULL,
MARCA VARCHAR(50) NOT NULL
);

ALTER TABLE VEICULOS ADD NOME VARCHAR(50) NOT NULL;
ALTER TABLE VEICULOS DROP COLUMN NOME;

CREATE TABLE IF NOT EXISTS MARCAS (
ID_MARCAS INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
PAIS VARCHAR(50) NOT NULL,
DATA_FUNDACAO DATE NOT NULL,
STATUS ENUM ('ATIVO', 'INATIVO') DEFAULT 'ATIVO',
CATEGORIA VARCHAR(50) NOT NULL
);

ALTER TABLE MARCAS ADD QUALIDADE VARCHAR(50) NOT NULL;
ALTER TABLE MARCAS DROP COLUMN QUALIDADE;

CREATE TABLE IF NOT EXISTS MODELOS (
ID_MODELOS INT AUTO_INCREMENT PRIMARY KEY,
CATEGORIA VARCHAR(50) NOT NULL,
COR VARCHAR(50) NOT NULL,
DATA_LANCAMENTO DATE NOT NULL,
NOME VARCHAR(50) NOT NULL,
VALOR DECIMAL(6,2) NOT NULL
);

ALTER TABLE MODELOS ADD TIPO VARCHAR(50) NOT NULL;
ALTER TABLE MODELOS DROP COLUMN TIPO;

CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
ID_FUNCIONARIOS INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
ESCALA TIME NOT NULL,
CPF VARCHAR(14) NOT NULL UNIQUE,
CARGO VARCHAR(50) NOT NULL
);

ALTER TABLE FUNCIONARIOS ADD IDADE INT NOT NULL;
ALTER TABLE FUNCIONARIOS DROP COLUMN IDADE;

CREATE TABLE IF NOT EXISTS SERVICOS (
ID_SERVICOS INT AUTO_INCREMENT PRIMARY KEY,
VALOR DECIMAL(6,2) NOT NULL, 
DATA DATETIME NOT NULL,
TIPO VARCHAR(50) NOT NULL,
NOME_FUNCIONARIO VARCHAR(50) NOT NULL,
VALIDADE DATETIME NOT NULL
);

ALTER TABLE SERVICOS ADD QUANTIDADE INT NOT NULL;
ALTER TABLE SERVICOS DROP COLUMN QUANTIDADE;

CREATE TABLE IF NOT EXISTS PECAS (
ID_PECAS INT AUTO_INCREMENT PRIMARY KEY,
TAMANHO VARCHAR(10) NOT NULL,
VALOR DECIMAL(6,2) NOT NULL,
NOME VARCHAR(50) NOT NULL,
MODELO VARCHAR(50) NOT NULL, 
VALIDADE DATETIME NOT NULL
);

ALTER TABLE PECAS ADD QUALIDADE VARCHAR(50) NOT NULL;
ALTER TABLE PECAS DROP COLUMN QUALIDADE;

CREATE TABLE IF NOT EXISTS ORDENS_SERVICOS (
ID_ORDENS_SERVICOS INT AUTO_INCREMENT PRIMARY KEY,
NOME_CLIENTE VARCHAR(50) NOT NULL,
TELEFONE VARCHAR(15) NOT NULL,
SITUACAO_CLIENTE VARCHAR(100) NOT NULL,
VALOR_TOTAL DECIMAL(6,2) NOT NULL,
TIPO_SERVICO VARCHAR(50) NOT NULL
);

ALTER TABLE ORDENS_SERVICOS ADD QUANTIDADE INT NOT NULL;
ALTER TABLE ORDENS_SERVICOS DROP COLUMN QUANTIDADE;

CREATE TABLE IF NOT EXISTS PAGAMENTOS (
ID_PAGAMENTOS INT AUTO_INCREMENT PRIMARY KEY,
COMPROVANTE INT NOT NULL,
VALOR_TOTAL DECIMAL(6,2) NOT NULL,
DATA_PAGAMENTO DATETIME NOT NULL,
METODO_PAGAMENTO ENUM ('CREDITO', 'DEBITO', 'PIX') DEFAULT 'CREDITO',
STATUS ENUM ('APROVADO', 'RECUSADO') DEFAULT 'APROVADO'
);

ALTER TABLE PAGAMENTOS ADD OBSERVACAO VARCHAR(50) NOT NULL;
ALTER TABLE PAGAMENTOS DROP COLUMN OBSERVACAO;

CREATE TABLE IF NOT EXISTS FORNECEDORES (
ID_FORNECEDORES INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
CNPJ_FORNECEDOR VARCHAR(18) NOT NULL UNIQUE,
EMAIL VARCHAR(50) NOT NULL,
TELEFONE VARCHAR(15) NOT NULL,
LOCALIZACAO VARCHAR(50) NOT NULL
);

ALTER TABLE FORNECEDORES ADD TEMPO_CONTRIBUICAO VARCHAR(20) NOT NULL;
ALTER TABLE FORNECEDORES DROP COLUMN TEMPO_CONTRIBUICAO;

RENAME TABLE MODELOS TO MODELOS_FAB;